### ISSUE TITLE
Write Personas

### ISSUE THREAD

**Issue by jona8690** [jona8690/Project-Web#9]
Personas Needed:
- [x] Students
- [x] Teachers
- [x] Admin

**Comment by jona8690** [comment]
Personas based on age or tech use?

Do we need personas based on tech use?

Do we need Admins?

**Comment by jona8690** [comment]
Due to changes in US we now require an admin.

**Comment by hedv0149** [comment]
Did the QA, needs some improvements:
Kathleen - No benefits.
Gustav  - Misses details about characteristics and behavior except that he is a teacher, no info about the age group, no benefits from our program.
Lily - Misses details about characteristics and behavior except that she is a worker in LærDansk, no info about the age group, no benefits from our program.

**Comment by jona8690** [comment]
Updated personas per https://github.com/jona8690/Project-Web/issues/9#issuecomment-342814817 closing this issue.

**Comment by roxa0188** [comment]
QA Approved
